### ISSUE TITLE
How to use this script?

### ISSUE THREAD

**Issue by heku** [bachp/Pristine-Git-CC#1]
Hi,
Very glad to find your script from http://stackoverflow.com/questions/2342131/how-to-bridge-git-to-clearcase , is there any post or demo to show us how to use this? we have a shared work directory which tracked by ClearCase and Git, so we want a script to help us synchronize the directory with these two side, I think your script must be designed for this, right? Thank you in advance.

**Comment by bachp** [comment]
Hi Heku

I haven't used it in a long time.
The only source of the script was [this](http://web.archive.org/web/20090503005209/http://genaud.net/2008/08/clearcase-globally-git-locally/) blog post.

I hope this helps you get started. And pull-requests for improved documentation are always welcome ;)

**Comment by heku** [comment]
Thank you for the answer.
